"""Add amount_due field

Revision ID: 233342170921
Revises: 
Create Date: 2024-04-09 15:51:22.548416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233342170921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('amount_due')

    # ### end Alembic commands ###
